s3:
    client_obj:
        put_object:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
        get_object:
            events:
                - EventName1
                - EventName2
            permissions:
                - PermissionName1
                - PermissionName2
        upload_file:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
    resource_obj:
        put_object:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
        get_object:
            events:
                - EventName1
                - EventName2
            permissions:
                - PermissionName1
                - PermissionName2
        upload_file:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
        
dynamodb:
    client_obj:
        put_item:
            events:
                - stream
            permissions:
                - PutItem
    resource_obj:
        put_item:
            events:
                - stream
            permissions:
                - PutItem

sqs:
    client_obj:
        send_message:
            events:
                - MessageSent
            permissions:
                - SendMessage
    resource_obj:
        send_message:
            events:
                - MessageSent
            permissions:
                - SendMessage

sns:
    client_obj:
        publish:
            events:
                - None
            permissions:
                - Publish
