s3:
    client_obj:
        list_objects:
            events:
                - None
            permissions:
                - ListObjects
        list_objects_v2:
            events:
                - None
            permissions:
                - ListObjects
        put_object:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
        get_object:
            events:
                - EventName1
                - EventName2
            permissions:
                - PermissionName1
                - PermissionName2
        upload_file:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
            events_filtering:
                - Key: 2
    resource_obj:
        all:
            events:
                - None
            permissions:
                - ListBucket
        delete:
            events:
                - None
            permissions:
                - DeleteObject
        put_object:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
        get_object:
            events:
                - EventName1
                - EventName2
            permissions:
                - PermissionName1
                - PermissionName2
        upload_file:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
        
dynamodb:
    client_obj:
        put_item:
            events:
                - stream
            permissions:
                - PutItem
            resources:
                - TableName: None
        scan:
            events:
                - None
            permissions:
                - Scan
    resource_obj:
        put_item:
            events:
                - stream
            permissions:
                - PutItem
        scan:
            events:
                - None
            permissions:
                - Scan

sqs:
    client_obj:
        send_message:
            events:
                - MessageSent
            permissions:
                - SendMessage
    resource_obj:
        send_message:
            events:
                - MessageSent
            permissions:
                - SendMessage

sns:
    client_obj:
        publish:
            events:
                - None
            permissions:
                - Publish

athena:
    client_obj: None
