s3:
    client_obj:
        list_objects:
            events:
                - None
            permissions:
                - ListObjects
                - List*
                - '*'
            resources:
                - Bucket: None
        list_objects_v2:
            events:
                - None
            permissions:
                - ListObjects
                - List*
                - '*'
            resources:
                - Bucket: None
        put_object:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
                - '*'
            resources:
                - Bucket: None
        get_object:
            events:
                - EventName1
                - EventName2
            permissions:
                - PermissionName1
                - PermissionName2 # Get* to be added
        upload_file:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
                - '*'
            resources:
                - Bucket: 1
            events_filtering:
                - Key: 2
    resource_obj:
        all:
            events:
                - None
            permissions:
                - ListBucket
                - List*
                - '*'
        delete:
            events:
                - None
            permissions:
                - DeleteObject
                - '*'
        put_object:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
                - '*'
        get_object:
            events:
                - EventName1
                - EventName2
            permissions:
                - PermissionName1
                - PermissionName2 # Get* to be added
        upload_file:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
                - '*'
        
dynamodb:
    client_obj:
        put_item:
            events:
                - stream
            permissions:
                - PutItem
                - '*'
            resources:
                - TableName: None
        scan:
            events:
                - None
            permissions:
                - Scan
                - '*'
            resources:
                - TableName: None
    resource_obj:
        put_item:
            events:
                - stream
            permissions:
                - PutItem
                - '*'
        scan:
            events:
                - None
            permissions:
                - Scan
                - '*'

sqs:
    client_obj:
        send_message:
            events:
                - MessageSent
            permissions:
                - SendMessage
                - '*'
            resources:
                - QueueUrl: None
    resource_obj:
        send_message:
            events:
                - MessageSent
            permissions:
                - SendMessage
                - '*'

sns:
    client_obj:
        publish:
            events:
                - None
            permissions:
                - Publish
                - Publish*
                - '*'
            resources:
                - TopicArn: None

athena:
    client_obj: None

acm:
    client_obj: None

apigateway:
    client_obj: None

apigatewaymanagementapi:
    client_obj: None

batch:
    client_obj: None

cloudformation:
    client_obj: None
    resource_obj: None

cloudtrail:
    client_obj: None

cloudwatch:
    client_obj: None
    resource_obj: None

codebuild:
    client_obj: None

codepipeline:
    client_obj: None

cognito-idp:
    client_obj: None

comprehend:
    client_obj: None

ec2:
    client_obj: None
    resource_obj: None

ecs:
    client_obj: None

efs:
    client_obj: None

elb:
    client_obj: None

elbv2:
    client_obj: None

events:
    client_obj: None

firehose:
    client_obj: None

glue:
    client_obj: None

iam:
    client_obj: None
    resource_obj: None

iot:
    client_obj: None

iot-data:
    client_obj: None

kinesis:
    client_obj: None

kms:
    client_obj: None

lambda:
    client_obj: None

lex-models:
    client_obj: None

lex-runtime:
    client_obj: None

lightsail:
    client_obj: None

logs:
    client_obj: None

mediaconvert:
    client_obj: None

polly:
    client_obj: None

quicksight:
    client_obj: None

rds:
    client_obj: None

rds-data:
    client_obj: None

rekognition:
    client_obj: None

resourcegroupstaggingapi:
    client_obj: None

route53:
    client_obj: None

sagemaker:
    client_obj: None

secretsmanager:
    client_obj: None

ses:
    client_obj: None

ssm:
    client_obj: None

stepfunctions:
    client_obj: None

sts:
    client_obj: None

support:
    client_obj: None

textract:
    client_obj: None
