s3:
    client_obj:
        put_object:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
        get_object:
            events:
                - EventName1
                - EventName2
            permissions:
                - PermissionName1
                - PermissionName2
        upload_file:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
    resource_obj:
        put_object:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
        get_object:
            events:
                - EventName1
                - EventName2
            permissions:
                - PermissionName1
                - PermissionName2
        upload_file:
            events:
                - ObjectCreated:*
            permissions:
                - PutObject
        
dynamodb:
    client_obj:
        put_item:
            events:
                - EventName1
                - EventName2
            permissions:
                - PermissionName1
                - PermissionName2
    
